# This file is part of Zettel.
#
# Copyright (c) Alexander Haase <ahaase@alexhaase.de>
#
# This project is licensed under the MIT License. For the full copyright and
# license information, please view the LICENSE file that was distributed with
# this source code.

providers:
  - name: zettel.provider.jira
    opts:
      server: https://jira.example.com
      auth:   ['user', 'Passw0rd']
      filter: assignee = currentUser() and status != done
      priorities:
        low:    LOW    # Priority.LOW
        medium: MEDIUM # Priority.MEDIUM
        high:   HIGH   # Priority.HIGH

  - name: zettel.provider.exchange
    opts:
      server:  mail.example.com
      account: hello@world.com
      credentials:
        username: user
        password: Passw0rd


# ========
# printing
# ========

template:
  name: zettel.template.default
  # opts:
  #   lang: de

printer:
  name: zettel.printer.escpos
  opts:
    type:      Usb
    idVendor:  0x04b8
    idProduct: 0x0202
    profile:   TM-T88III
